create table if not exists public.learning_platform_state (
  id text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.evaluasi (
  id text primary key,
  title text not null,
  description text,
  is_active boolean not null default true,
  updated_at timestamptz default now()
);

create table if not exists public.materi (
  id text primary key,
  title text not null,
  badge text,
  subtitle text,
  body text,
  order_index integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.video_pembelajaran (
  id text primary key,
  title text not null,
  duration text,
  tag text,
  embed_url text,
  description text,
  order_index integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.document_materials (
  id text primary key,
  title text not null,
  description text,
  file_name text,
  file_url text,
  file_type text,
  order_index integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.tugas (
  id text primary key,
  title text not null,
  badge text,
  description text,
  instructions text[] not null default '{}'::text[],
  starter_code text not null default '',
  order_index integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.soal_evaluasi (
  id text primary key,
  evaluation_id text not null references public.evaluasi(id) on delete cascade,
  question text not null,
  options text[] not null default '{}'::text[],
  correct_answer text not null,
  order_index integer not null default 0,
  updated_at timestamptz default now()
);

create table if not exists public.hasil_evaluasi (
  id bigint generated by default as identity primary key,
  student_name text not null,
  score integer not null,
  answers jsonb not null default '{}'::jsonb,
  submitted_at timestamptz default now()
);

create table if not exists public.jawaban_tugas (
  id bigint generated by default as identity primary key,
  assignment_id text not null references public.tugas(id) on delete cascade,
  student_name text not null,
  code text not null default '',
  submitted_at timestamptz default now(),
  status text not null default 'submitted'
);

create table if not exists public.users (
  id text primary key,
  name text not null,
  email text not null,
  role text not null,
  updated_at timestamptz default now()
);

create table if not exists public.profiles (
  id text primary key,
  user_id text,
  role text not null,
  name text not null,
  email text not null,
  profile_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

create table if not exists public.invitation_codes (
  id text primary key,
  code text not null unique,
  created_by text not null,
  used_by text,
  used_at timestamptz,
  expires_at timestamptz,
  status text not null default 'active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_evaluasi_is_active on public.evaluasi (is_active);
create index if not exists idx_materi_order on public.materi (order_index);
create index if not exists idx_video_order on public.video_pembelajaran (order_index);
create index if not exists idx_document_materials_order on public.document_materials (order_index);
create index if not exists idx_tugas_order on public.tugas (order_index);
create index if not exists idx_soal_evaluasi_order on public.soal_evaluasi (evaluation_id, order_index);
create index if not exists idx_hasil_evaluasi_submitted on public.hasil_evaluasi (submitted_at desc);
create index if not exists idx_jawaban_tugas_submitted on public.jawaban_tugas (assignment_id, submitted_at desc);
create index if not exists idx_users_email on public.users ((lower(email)));
create index if not exists idx_profiles_email on public.profiles ((lower(email)));
create index if not exists idx_invitation_codes_code on public.invitation_codes (code);
create index if not exists idx_invitation_codes_status on public.invitation_codes (status);

alter table public.learning_platform_state enable row level security;
alter table public.evaluasi enable row level security;
alter table public.materi enable row level security;
alter table public.video_pembelajaran enable row level security;
alter table public.document_materials enable row level security;
alter table public.tugas enable row level security;
alter table public.soal_evaluasi enable row level security;
alter table public.hasil_evaluasi enable row level security;
alter table public.jawaban_tugas enable row level security;
alter table public.users enable row level security;
alter table public.profiles enable row level security;
alter table public.invitation_codes enable row level security;

drop policy if exists "Allow read access for all users" on public.learning_platform_state;
drop policy if exists "Allow insert and update for all users" on public.learning_platform_state;
drop policy if exists "Allow update for all users" on public.learning_platform_state;
create policy "Allow read access for all users" on public.learning_platform_state for select using (true);
create policy "Allow insert and update for all users" on public.learning_platform_state for insert with check (true);
create policy "Allow update for all users" on public.learning_platform_state for update using (true) with check (true);

drop policy if exists "Allow read access for all users" on public.evaluasi;
drop policy if exists "Allow insert and update for all users" on public.evaluasi;
drop policy if exists "Allow update for all users" on public.evaluasi;
create policy "Allow read access for all users" on public.evaluasi for select using (true);
create policy "Allow insert and update for all users" on public.evaluasi for insert with check (true);
create policy "Allow update for all users" on public.evaluasi for update using (true) with check (true);
create policy "Allow delete for all users" on public.evaluasi for delete using (true);

drop policy if exists "Allow read access for all users" on public.materi;
drop policy if exists "Allow insert and update for all users" on public.materi;
drop policy if exists "Allow update for all users" on public.materi;
drop policy if exists "Allow delete for all users" on public.materi;
create policy "Allow read access for all users" on public.materi for select using (true);
create policy "Allow insert and update for all users" on public.materi for insert with check (true);
create policy "Allow update for all users" on public.materi for update using (true) with check (true);
create policy "Allow delete for all users" on public.materi for delete using (true);

drop policy if exists "Allow read access for all users" on public.video_pembelajaran;
drop policy if exists "Allow insert and update for all users" on public.video_pembelajaran;
drop policy if exists "Allow update for all users" on public.video_pembelajaran;
drop policy if exists "Allow delete for all users" on public.video_pembelajaran;
create policy "Allow read access for all users" on public.video_pembelajaran for select using (true);
create policy "Allow insert and update for all users" on public.video_pembelajaran for insert with check (true);
create policy "Allow update for all users" on public.video_pembelajaran for update using (true) with check (true);
create policy "Allow delete for all users" on public.video_pembelajaran for delete using (true);

drop policy if exists "Allow read access for all users" on public.document_materials;
drop policy if exists "Allow insert and update for all users" on public.document_materials;
drop policy if exists "Allow update for all users" on public.document_materials;
drop policy if exists "Allow delete for all users" on public.document_materials;
create policy "Allow read access for all users" on public.document_materials for select using (true);
create policy "Allow insert and update for all users" on public.document_materials for insert with check (true);
create policy "Allow update for all users" on public.document_materials for update using (true) with check (true);
create policy "Allow delete for all users" on public.document_materials for delete using (true);

drop policy if exists "Allow read access for all users" on public.tugas;
drop policy if exists "Allow insert and update for all users" on public.tugas;
drop policy if exists "Allow update for all users" on public.tugas;
drop policy if exists "Allow delete for all users" on public.tugas;
create policy "Allow read access for all users" on public.tugas for select using (true);
create policy "Allow insert and update for all users" on public.tugas for insert with check (true);
create policy "Allow update for all users" on public.tugas for update using (true) with check (true);
create policy "Allow delete for all users" on public.tugas for delete using (true);

drop policy if exists "Allow read access for all users" on public.soal_evaluasi;
drop policy if exists "Allow insert and update for all users" on public.soal_evaluasi;
drop policy if exists "Allow update for all users" on public.soal_evaluasi;
drop policy if exists "Allow delete for all users" on public.soal_evaluasi;
create policy "Allow read access for all users" on public.soal_evaluasi for select using (true);
create policy "Allow insert and update for all users" on public.soal_evaluasi for insert with check (true);
create policy "Allow update for all users" on public.soal_evaluasi for update using (true) with check (true);
create policy "Allow delete for all users" on public.soal_evaluasi for delete using (true);

drop policy if exists "Allow read access for all users" on public.hasil_evaluasi;
drop policy if exists "Allow insert for all users" on public.hasil_evaluasi;
create policy "Allow read access for all users" on public.hasil_evaluasi for select using (true);
create policy "Allow insert for all users" on public.hasil_evaluasi for insert with check (true);

drop policy if exists "Allow read access for all users" on public.jawaban_tugas;
drop policy if exists "Allow insert and update for all users" on public.jawaban_tugas;
drop policy if exists "Allow update for all users" on public.jawaban_tugas;
create policy "Allow read access for all users" on public.jawaban_tugas for select using (true);
create policy "Allow insert and update for all users" on public.jawaban_tugas for insert with check (true);
create policy "Allow update for all users" on public.jawaban_tugas for update using (true) with check (true);

drop policy if exists "Allow read access for all users" on public.users;
drop policy if exists "Allow insert and update for all users" on public.users;
drop policy if exists "Allow update for all users" on public.users;
create policy "Allow read access for all users" on public.users for select using (true);
create policy "Allow insert and update for all users" on public.users for insert with check (true);
create policy "Allow update for all users" on public.users for update using (true) with check (true);

drop policy if exists "Allow read access for all users" on public.profiles;
drop policy if exists "Allow insert and update for all users" on public.profiles;
drop policy if exists "Allow update for all users" on public.profiles;
create policy "Allow read access for all users" on public.profiles for select using (true);
create policy "Allow insert and update for all users" on public.profiles for insert with check (true);
create policy "Allow update for all users" on public.profiles for update using (true) with check (true);

drop policy if exists "Allow read access for all users" on public.invitation_codes;
drop policy if exists "Allow insert and update for all users" on public.invitation_codes;
drop policy if exists "Allow update for all users" on public.invitation_codes;
create policy "Allow read access for all users" on public.invitation_codes for select using (true);
create policy "Allow insert and update for all users" on public.invitation_codes for insert with check (true);
create policy "Allow update for all users" on public.invitation_codes for update using (true) with check (true);

insert into public.evaluasi (id, title, description, is_active, updated_at)
values (
  'default-evaluation',
  'Kelas Web Development',
  'Kelas interaktif untuk belajar UI, Next.js, dan integrasi data.',
  true,
  now()
) on conflict (id) do nothing;

insert into public.materi (id, title, badge, subtitle, body, order_index, updated_at)
values
  ('slide-1', 'Pengenalan Platform', 'Dasar', 'Memahami alur belajar', 'Belajar bagaimana platform ini membantu Anda mengorganisir pembelajaran.', 0, now()),
  ('slide-2', 'UI dan UX', 'UI', 'Membangun antarmuka yang menarik', 'Latih keterampilan desain dan pengalaman pengguna dalam satu proyek.', 1, now()),
  ('slide-3', 'Integrasi Data', 'Data', 'Menghubungkan frontend dan backend', 'Pelajari cara mengirim dan mengambil data secara aman.', 2, now())
on conflict (id) do nothing;

insert into public.video_pembelajaran (id, title, duration, tag, embed_url, description, order_index, updated_at)
values
  ('video-1', 'Mengenal Next.js', '12:30', 'Next.js', 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'Pengantar singkat tentang Next.js dan arsitektur aplikasi.', 0, now()),
  ('video-2', 'Supabase untuk Pemula', '08:45', 'Supabase', 'https://www.youtube.com/embed/ScMzIvxBSi4', 'Cara menghubungkan aplikasi dengan Supabase.', 1, now())
on conflict (id) do nothing;

insert into public.tugas (id, title, badge, description, instructions, starter_code, order_index, updated_at)
values (
  'assignment-1',
  'Membuat Halaman Profil',
  'Tugas',
  'Bangun halaman profil sederhana dengan desain responsif.',
  ARRAY['Buat komponen profil', 'Tampilkan nama, email, dan role', 'Gunakan Tailwind CSS'],
  'export default function ProfilePage() {\n  return <div />;\n}',
  0,
  now()
) on conflict (id) do nothing;

insert into public.soal_evaluasi (id, evaluation_id, question, options, correct_answer, order_index, updated_at)
values
  ('question-1', 'default-evaluation', 'Manakah yang paling tepat untuk memecah UI menjadi bagian yang rapi?', ARRAY['Komponen modular', 'Satu file besar', 'Inline style semua', 'Tidak perlu struktur'], 'Komponen modular', 0, now()),
  ('question-2', 'default-evaluation', 'Apa keuntungan utama menghubungkan ke Supabase?', ARRAY['Data tersimpan terpusat', 'Tidak perlu API', 'Lebih kecil dari HTML', 'Semua jawaban benar'], 'Data tersimpan terpusat', 1, now()),
  ('question-3', 'default-evaluation', 'Apa arti dari SSR dalam Next.js?', ARRAY['Server Side Rendering', 'Static Style Rules', 'Simple Script Runtime', 'Server Storage Request'], 'Server Side Rendering', 2, now()),
  ('question-4', 'default-evaluation', 'Framework frontend yang paling sering dipakai bersama Next.js adalah?', ARRAY['React', 'Laravel', 'Django', 'Flask'], 'React', 3, now()),
  ('question-5', 'default-evaluation', 'Apa fungsi utama Tailwind CSS?', ARRAY['Mempermudah styling dengan utility class', 'Mengolah database', 'Mengganti JavaScript', 'Menyimpan file gambar'], 'Mempermudah styling dengan utility class', 4, now()),
  ('question-6', 'default-evaluation', 'Apa yang dimaksud dengan state pada komponen?', ARRAY['Data yang bisa berubah selama aplikasi berjalan', 'File CSS', 'URL halaman', 'Library gambar'], 'Data yang bisa berubah selama aplikasi berjalan', 5, now()),
  ('question-7', 'default-evaluation', 'Di Next.js, untuk membuat halaman baru biasanya digunakan?', ARRAY['Folder dan file page.tsx', 'Folder gambar saja', 'File .env saja', 'Database SQL'], 'Folder dan file page.tsx', 6, now()),
  ('question-8', 'default-evaluation', 'Kapan useEffect biasanya dipakai?', ARRAY['Saat ingin menjalankan efek samping', 'Saat membuat variabel CSS', 'Saat mengatur route', 'Saat menghapus file'], 'Saat ingin menjalankan efek samping', 7, now()),
  ('question-9', 'default-evaluation', 'Apa fungsi props pada komponen React?', ARRAY['Mengirim data dari parent ke child', 'Menghapus komponen', 'Menyimpan gambar', 'Membuat komentar'], 'Mengirim data dari parent ke child', 8, now()),
  ('question-10', 'default-evaluation', 'Data pengguna yang sensitif biasanya disimpan di?', ARRAY['Database aman seperti Supabase', 'File HTML biasa', 'Komentar di kode', 'LocalStorage tanpa validasi'], 'Database aman seperti Supabase', 9, now()),
  ('question-11', 'default-evaluation', 'Apa tujuan dari API route?', ARRAY['Menyediakan endpoint backend dari aplikasi', 'Mengatur layout halaman', 'Membuat icon', 'Menjalankan test otomatis'], 'Menyediakan endpoint backend dari aplikasi', 10, now()),
  ('question-12', 'default-evaluation', 'Mengapa data hardcoded kurang baik untuk aplikasi nyata?', ARRAY['Karena sulit dikelola dan diperbarui', 'Karena lebih cepat dari database', 'Karena tidak bisa ditampilkan', 'Karena tidak memakai JavaScript'], 'Karena sulit dikelola dan diperbarui', 11, now()),
  ('question-13', 'default-evaluation', 'Apa kegunaan localStorage dalam frontend?', ARRAY['Menyimpan data sederhana di browser', 'Mengirim email', 'Memproses gambar', 'Membuat server'], 'Menyimpan data sederhana di browser', 12, now()),
  ('question-14', 'default-evaluation', 'Apa yang dimaksud dengan reactivity dalam UI?', ARRAY['Tampilan berubah saat data berubah', 'Hanya memuat halaman pertama', 'Menghapus event listener', 'Mengubah ukuran font saja'], 'Tampilan berubah saat data berubah', 13, now()),
  ('question-15', 'default-evaluation', 'Mana yang termasuk library UI populer?', ARRAY['Tailwind CSS', 'Node.js', 'MongoDB', 'Vercel'], 'Tailwind CSS', 14, now()),
  ('question-16', 'default-evaluation', 'Apa yang dimaksud dengan responsive design?', ARRAY['Tampilan yang menyesuaikan ukuran layar', 'Hanya untuk desktop', 'Hanya untuk mobile', 'Tidak memerlukan CSS'], 'Tampilan yang menyesuaikan ukuran layar', 15, now()),
  ('question-17', 'default-evaluation', 'Apa manfaat utama Server Components di Next.js?', ARRAY['Membuat rendering lebih efisien dan aman', 'Menghapus semua CSS', 'Mempercepat koneksi internet', 'Mengganti Supabase'], 'Membuat rendering lebih efisien dan aman', 16, now()),
  ('question-18', 'default-evaluation', 'Apa fungsi utama form handling dalam aplikasi web?', ARRAY['Menerima input pengguna dan mengolahnya', 'Mengganti warna tema', 'Menutup tab browser', 'Menyimpan video'], 'Menerima input pengguna dan mengolahnya', 17, now()),
  ('question-19', 'default-evaluation', 'Apa arti accessibility dalam pengembangan web?', ARRAY['Membuat aplikasi lebih mudah diakses semua pengguna', 'Menghapus semua tombol', 'Membatasi fitur', 'Mengurangi ukuran file'], 'Membuat aplikasi lebih mudah diakses semua pengguna', 18, now()),
  ('question-20', 'default-evaluation', 'Cara terbaik untuk mengelola data asinkron di frontend adalah?', ARRAY['Menggunakan state dan efek yang terkontrol', 'Menghapus semua API', 'Mengganti semua teks', 'Menggunakan satu file CSS saja'], 'Menggunakan state dan efek yang terkontrol', 19, now())
on conflict (id) do nothing;

insert into public.users (id, name, email, role, updated_at)
values
  ('guru-demo', 'Guru', 'guru@mediapembelajaran.com', 'guru', now()),
  ('siswa-demo', 'Siswa', 'siswa@mediapembelajaran.com', 'siswa', now())
on conflict (id) do nothing;

insert into public.profiles (id, user_id, role, name, email, profile_data, updated_at)
values
  ('guru-profile', 'guru-demo', 'guru', 'Guru', 'guru@mediapembelajaran.com', '{"last_login": "1970-01-01T00:00:00Z", "source": "seed"}', now()),
  ('siswa-profile', 'siswa-demo', 'siswa', 'Siswa', 'siswa@mediapembelajaran.com', '{"last_login": "1970-01-01T00:00:00Z", "source": "seed"}', now())
on conflict (id) do nothing;

insert into public.learning_platform_state (id, value, updated_at)
values (
  'default',
  '{"className":"Kelas Web Development","classDescription":"Kelas interaktif untuk belajar UI, Next.js, dan integrasi data.","role":"siswa"}',
  now()
) on conflict (id) do nothing;
